ocropus-hocr
Tweaks so that I'm able to run `ocropus-hocr` on my machine:
- Remove unused `matplotlib` import.
- Pare down overly-broad `pylab` import. `from pylab import *` segfaults on my Mac.
I removed the `FIXME` because it looks fixed. I removed the `cseg` line because it's not true.
=> Simplify imports for ocropus-hocr

ocropus-rpred
this updates avoid error message received when writing characters like ä
=> Update ocropus-rpred: saving alocs and llocs

README.md, README_OSX.md
Compile flag `-fopenmp` is for `gcc`, but not works on `clang`
=> Patch for OS X / clang

ocropus-linegen
The font may be saved below in the file tree and therefore the new direcotry will start with `../` which is by default a invisible file. E.g.
```
ocropus-linegen -t ../text-generation/text.txt -f ../text-generation/font.ttf -m 5 -o ../text-generation/linegen
```
will create a directory `/text-generation/linegen/.._font/` which is mostly invisible and the naming in this case is really ugly.
This should be an easy and safe fix.
=> Clean name for new output directory

ocrolib/toplevel.py
Fixed this issue:
`<ndarray-7feb15be2060 (380, 550) uint64 [0,1105]> of type <type 'numpy.ndarray'>: array must contain integer values`
=> added uint64 to integer types

ocrolib/common.py
As of v3.0.x of Pillow baa5143394708704328dcd46b0387f36a276a762 the deprecated `tostring()` function is no longer an alias for `tobytes()`.
Tested this successfully with `./run-test` in two setups, one with Pillow 2.9.0 where it worked before and after the change, one with 3.0.0, where worked just with `tobytes()`
This should not conflict with any setup with a version of pillow >= 2.0
=> Changed tostring() to tobytes() because the former is deprecated

ocropus-gpageseg
... to avoid numpy type casting errors. 
Came across the same errors mentioned in Ocropy's Google Groups forum in October 2015:
https://groups.google.com/d/msg/ocropus/U4_MNVRMKxA/b7iwyKbEBQAJ
Apparently numpy doesn't handle casting in augmented assignment in the same way that it does when multiplying on the right hand side of the assignment.
=> removed augmented assignment in ocropus-gpageseg

PACKAGES
Installing firefox pulls in a lot of dependencies that are not needed in a headless setup.
=> firefox is not needed for ocropy to be installed

ocropus-gpageseg
We were trying to cast "scale" to a string then print it as a float.
=> Fix for 'TypeError: float argument required, not str'

ocropus-gtedit
Now, Firefox (and probably other browsers) will propose to use the
actual filename as the template for "Save page as".
=> [gtedit] Use HTML file name instead of "Correction", #84

setup.py
While it's sensible to remind the user to install a model and have available models at build time installed to /usr/share/ocropus, it should be possible to install ocropy without any models. They can always be provided via CLI flag.
This patch will install **all** `models/*.pyrnn.gz` files that are found, not just the default. But if none are found, it will still succeed.
=> python setup.py install should not fail without models

ocropus-gpageseg, ocropus-nlbin, ocropus-rpred
This cleans up the print_* calls in those files that redundantly cast numbers to string (as mentioned in #103)
```python
"%s" % (str(1))
"%d" % (1)
fname+": %d" % 3
"%s: %d" % (fname, 3)
```
=> Replaces multi-var str() concat with %-format

ocropus-nlbin
ocropus-nlbin causes
```
/usr/lib/python2.7/dist-packages/numpy/core/numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer
will result in an error in the future
a = empty(shape, dtype, order)
```
and tries to suppress it:
```python
v = morphology.binary_dilation(v,structure=ones((e*50,1)))
```
`e` is a float, so the first tuple element will also be a float. But it should be an integer.
numpy 1.11.0 at least outputs a `VisibleDeprecationWarning` which won't be filtered.
=> nlbin: fix VisibleDeprecationWarning about non-integers

ocropus-linegen
=> From PIL import

ocrolib/lstm.py, ocropus-rpred
This PR will give `ocropus-rpred` a new option `--probabilities` which will additionally save for each line a file `.prob` which contains the character probabilities, e.g.
```
root@939002a1af8e:/ocropy# ocropus-rpred tests/1175-01002b.png --probabilities
INFO:
INFO:  ########## /usr/local/bin/ocropus-rpred tests/1175-01002b.png --probabi
INFO:
INFO:  #inputs: 1
INFO:  tests/1175-01002b.png:crcasing oricntation dispersion of a single sct of
```
which will also save the file `1175-01002b.prob` which looks like
```
c	0.979626931378
r	0.995782592762
c	0.947235609157
a	0.996203434919
s	0.991683733363
i	0.993947589753
n	0.994791900459
g	0.966814216763
0.995118403987
o	0.99320397717
r	0.992937184296
i	0.995907285691
c	0.703712835111
n	0.99234998498
t	0.992499281063
...
```
I simplified [my …
=> Add new option --probabilities in ocropus-rpred

ocrolib/common.py, ocrolib/exceptions.py, ocrolib/lstm.py, ocropus-gpageseg, ocropus-rpred
* Move exceptions to its own module
* Make all imports explicit, so static code analysis tools like pyflakes can help
* remove redundant deprecated decorators
* Remove old load_components
* Remove old draw_pseg/draw_aligned
=> Cleanup imports in common.py, lstm.py, extract exceptions

.travis.yml, README.md, run-coverage, run-rtrain, run-test
A very simple setup for testing via Travis. It uses Miniconda to install dependencies and then runs the test script. I originally tried a straight install, but compiling SciPy took so long, it [ran out of build time](https://travis-ci.org/QuLogic/ocropy/builds/62312903). The conda install is much much quicker.
You will of course have to enable Travis for your repo before this has a real effect. And it doesn't really check whether the result correct, only that something is produced, but that's how the existing test script is. One could also do coverage testing using the other script and coveralls.io, but that's something for a another PR.
=> Travis CI builds

ocropus-gpageseg
This parameter was never used in the page segmentation,
but it is only used in the binarization and some older scripts.
=> Delete unused and suppress obsolete parameters in ocropus-gpageseg

ocrolib/lstm.py
This should avoid (hopefully) some possible FloatingPointError overflow errors.
The sigmoid function ffunc is for any x<-20 and x>20 already 0 resp. 1 up to 10^-9
and cutting will therefore not change the function substantially.
This idea is from @tmbdev in https://github.com/tmbdev/ocropy/issues/5#issuecomment-65329170
Implemented first in https://github.com/tmbdev/ocropy/issues/49#issuecomment-139919235
Additional infos from https://github.com/tmbdev/ocropy/issues/79#issue-126999594
=> Clip exponential in ffunc to avoid overflow

ocrolib/common.py
This seems to solve #88 and allows to run page segmentation also in smaller images (less than 600x600), by using the `-n` option which deactivate the checks. The function `write_page_segmentation` should IMO not depend on the size of the image. Moreover, the check is now equal to the one for the function `read_page_segmentation` (cf. some lines above).
=> Change checks for write_page_segmentation

ocropus-gpageseg
I looks as if pylab.find and np.where work slightly different.
=> Fix regression in ocropus-gpageseg #251

ocrolib/common.py
=> :bug: Do not add $datarootdir/ocropus to model search path if it is None

ocrolib/lstm.py, ocrolib/utils.py
Use numpy.einsum() for sumouter and sumprod functions.
=> Replace native code with regular functions

ocropus-rtrain, run-test-ci
Together with @uvius I added the option to pass the training images through a file, avoiding the "Argument list too long" error when passing too many files.
This allows the user to pass as many files as he wants to ocropus-rtrain, avoiding the `argument list too long` error of the shell, as in Issue #93.
=> Added option to load training data through file

ocrolib/hocr.py, setup.py
New tags/releases were created now retroperspectively, but we should try to continue that better just in time. With the new commit which gets rid of the native code, we can plan a new version 1.3.2.
This is on hold until #269 is solved. Any more testing of the current state would also be appreciated.
(After merging this commit can then be tagged with `v1.3.2`.)
=> Bump version to 1.3.2

ocropus-gpageseg
It is now important that the True, False values
in the matrix are transformed to numbers before
passing them to imsave function.
This fixes #299.
=> Fix TypeError with new numpy version
