ocropus/ocropy

- README.md
- ocrolib/common.py
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix some typos

- README.md
Just a little fix to the virtualenv launch instructions.
> Updating virtualenv instructions

- PACKAGES
This is a rebase aggainst current master of #109 by @kba
> opencv is used in the OLD scripts but not for the installed tools

- ocrolib/hocr.py
> hocr metadata: bump version 0.4 -> 1.0, ocropus -> ocropy

- ocropus-rtrain
> Document --start option in rtrain

- .github/ISSUE_TEMPLATE.md
An [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) to make reporting bugs/problems/feature requests more structured.
> Issue template, mostly for bug reports

- ocrolib/common.py
- ocrolib/lineest.py
- ocrolib/lstm.py
- ocrolib/morph.py
- ocropus-linegen
- ocropus-nlbin
These two import statements were hidden
in the main content below, but already
present in the beginning, i.e. they were
duplicate.
> Clean up import statements

- ocropus-hocr
- properties "image" and "bbox" for the "ocr_page" element.
- correct orientation of coordinate system
> Made output more compatible to the hOCR spec.

- ocrolib/morph.py
> Remove tabs in source

- OLD/ocrolib/h5utils.py
- OLD/ocrolib/ngraphs.py
- examples/rnnlib-vs-ocropy.ipynb
- ocrolib/common.py
- ocrolib/edist.py
- ocrolib/extras/fgen.py
- ocrolib/extras/lru.py
- ocrolib/lineest.py
- ocrolib/lstm.py
- ocrolib/morph.py
- ocrolib/native.py
- ocrolib/psegutils.py
- ocrolib/toplevel.py
- ocropus-dewarp
- ocropus-econf
- ocropus-errs
- ocropus-gpageseg
- ocropus-gtedit
- ocropus-linegen
- ocropus-lpred
- ocropus-ltrain
- ocropus-nlbin
- ocropus-rpred
- ocropus-rtrain
- ocropus-visualize-results
- setup.py
I split this out of #114 for easier review.
There are some changes to OLD because they were there originally, but I assume there's no need to really update the rest of them. Though I wonder why you don't just delete those files? That's why you've got git history...
> py3k: Use print function instead of statement

- ocrolib/extras/cairoextras.py
- ocrolib/toplevel.py
- ocropus-lpred
- ocropus-ltrain
> py3k: Use new-style exceptions.

- ocrolib/edist.py
- ocropus-econf
- tests/run-unit
> [econf] Handle possibility that filtered GT is empty

- ocropus-econf
- ocropus-errs
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Print summaries to stdout instead of stderr 

- ocrolib/morph.py
- ocropus-gpageseg
Implementation of **Possible Solution** specified in issue #171
> Detect the passed number of separators

- ocropus-gpageseg
- ocropus-nlbin
* see also #137
* the other two lines contained strange symbols coded as FF or points in the editor in GitHub:
> Unused function select_regions in ocropus-nlbin

- README.md
See also http://stackoverflow.com/questions/35770134/python-virtualenv-cant-run-bash-script-properly
> Update installation steps for virtualenv

- ocrolib/lineest.py
This solves #55 by extending the fix from @braddockcg .
> Dewarp padding

- .travis.yml
- tests/run-unit
Make sure that unit tests are tested during CI.
> Unit tests

- ocrolib/morph.py
- ocrolib/toplevel.py
> Extend segmentation check for uint64 as well

- ocropus-gpageseg
> Fix check for nrm.png files in ocropus-pageseg --gray

- ocrolib/common.py
@kba Any reason we haven't yet merged this branch into master? Moreover, it seems to fix one issue...
> write_text should not fail for empty lines, fix #243
